### ISSUE TITLE
Breaking change on upcoming v0.13.0 release

### ISSUE THREAD

**Issue by khos2ow** [looztra/asdf-terraform-docs#11]
As of upcoming `v0.13.0` terraform-docs won't distribute standalone binaries (https://github.com/terraform-docs/terraform-docs/issues/454). Available formats are:

- Windows: `.zip`
- everything else: `tar.gz`

**Comment by jrnt30** [comment]
This is addressed in https://github.com/looztra/asdf-terraform-docs/pull/13

**Comment by looztra** [comment]
closing, fixed by #13
