### ISSUE TITLE
CI only checks version 0.10.1

### ISSUE THREAD

**Issue by jthegedus** [looztra/asdf-terraform-docs#12]
The `asdf` action is only testing version `0.10.1` of the `terraform-docs` installed by this tool.

This means new values returned by `list-all` are not being checked. This results in other issues like #11 

The change required for CI to check the `latest` versions as they release is:

```diff
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: terraform-docs --version
-         version: 0.10.1
```

**Comment by looztra** [comment]
fixed by #16
