### ISSUE TITLE
failures when downloading with `v` prefix

### ISSUE THREAD

**Issue by bdellegrazie** [looztra/asdf-terraform-docs#9]
Hi,

Prior to the latest version of the plugin it worked normally when the versions exactly matched the upstream tags (i.e. with the `v`) prefix. It now does not - list all reports all versions without the `v` prefix.

I can see an attempt at handling the `v` prefix with `__SHORT_VERSION__` substitutions however in the places where these are substituted the source strings use `v__VERSION__` instead of `v__SHORT_VERSION__` which would work in either situation.

Any chance you could take another look so the plugin will support `v` prefixed versions and work correctly in either case?

Thanks in advance!

**Comment by paulmarsicloud** [comment]
I too am encountering this issue: 

```
cat .tool-versions
terraform-docs v0.8.2
```

```
asdf install
\e[36m[2021-02-18 15:01:18] INFO: Downloading [terraform-docs] from https://github.com/terraform-docs/terraform-docs/releases/download/vv0.8.2/terraform-docs-vv0.8.2-darwin-amd64
```

Double `v` added in that url above when it should be https://github.com/terraform-docs/terraform-docs/releases/download/v0.8.2/terraform-docs-v0.8.2-darwin-amd64

**Comment by Andrew-Wichmann** [comment]
ditto

**Comment by bdellegrazie** [comment]
There are further issues now that the archive is being compressed and my fix no longer works.
